const content = [
  "After the gem surrounding it had shattered into pieces, the flower bud that was revealed slowly bloomed open. As each petal unfurled one by one, the red fragments of jewel clinging to them crumbled into powder and blew away. The Sage closed her eyes for a few moments before opening them to look down at Mary.",
  "Eventually, Mary’s petals had unfurled completely. At that moment, the Sage slowly lifted Mary in front of her.",
  "Whoooosh!",
  "The drifting red powder swirled and floated up into the air.",
  "Pop!",
  "The powder was transformed into petals once more, which then poured down from the sky like rain. Sienna watched this scene happen with wide eyes. The petals currently raining down in front of her eyes were the same petals that had appeared last time when she had first created soul power.",
  "“As expected, it really was you, wasn’t it?” Sienna let out a snort as she stared accusingly at the Sage.",
  "The Sage, who was looking down at Mary with a satisfied smile, let out a soft laugh at Sienna’s accusatory words and nodded without hesitation.",
  "“Was my guidance unwelcome?” the Sage gently teased.",
  "The Sage laughed, “Ahahaha. If that’s the case, then it’s quite fortunate. Although I only provided some brief guidance, it seems that you were able to comprehend it very quickly, Junior. All I did was give you a slight nudge in the right direction, but you were immediately able to grasp the power that I guided you towards.”",
  "“What’s so impressive about that? If I was that lacking in comprehension, I wouldn’t have been able to become the level of wizard that I am in the first place,” Sienna said with another proud snort. But from the way that her chin had gradually risen upwards and her shoulders were thrown back, it seemed like she was happy to receive such acknowledgment.",
  "“Why was that staff in the possession of the Demon King of Incarceration?” Kristina remembered to ask this question once her surprise had settled. She had also been staring at the scene around her with wide eyes,",
  "It was only natural for such a question to be asked, as it was an important mystery that needed answering. Also, they had wanted Edsillon to ask the elven Ancestor Spirits about the origins of the Bloody Mary in the first place.",
  "“It was given to him for it to arrive safely in the new era,” the Sage replied. “I left a record of my magic in Mary. To tell the truth, the magic within that staff cannot be used by anyone I wouldn’t approve of, so it would be of little use to fools who might call themselves wizards but lack any true understanding of magic.”",
  "This was an extremely arrogant statement for her to make. However, Sienna had no choice but to agree with the Sage’s words reluctantly.",
  "From what she had seen of the Ancient Magic that the Sage had recorded in the very depths of the Bloody Mary, with its lack of any sort of formulas, it was similar to the miracles that priests requested from their gods… or elven magic that entrusted the caster’s wishes to mana itself.",
  "“Even if it only records magic that not everyone has access to, my Mary still has great value in its own right. I didn’t want to leave Mary to be swept away by the waves of Destruction, so I… handed Mary over to that Ancient Demon,” the Sage paused for a few moments before letting out a laugh. “There wasn’t any sort of promise involved in that exchange. When that Ancient Demon came looking for me to satisfy his greed, I told him not to insult me, then… ahaha, I just gave him my Mary instead. However, while I’m thankful that Ancient Demon didn’t just shatter my staff, the long years it spent in his possession has unfortunately left it looking like this.”",
  "“His greed, you say,” Eugene said with a frown, feeling disturbed by that choice of words. While glancing over to the Sage, he asked, “What kind of greed led the Demon King of Incarceration to come looking for you?”",
  "“He didn’t covet me in a physical or sexual way, so there’s no need to be jealous,” the Sage replied with a mischievous smile.",
  "Eugene’s face twisted into a scowl at this sudden, crude teasing. However, before he could express his anger, the Sage continued speaking.",
  "“The Ancient Demon wanted my soul,” the Sage revealed.",
  "“Your soul?” Eugene repeated doubtfully.",
  "“He is the Demon King of all Demon Kings. He is a truly ancient Demon King who has seen an unknown number of destroyed worlds pass him by. If he truly wishes to, he can even collect the souls of other Demon Kings. That way, he can take them with him as he moves on to the next era with all of the souls that he has collected…,” the Sage trailed off ominously.",
  "This ability was what raised the Demon King of Incarceration above all the other Demon Kings. Unlike the other Demon Kings, the Demon King of Incarceration could partially resist the destruction of the world.",
  "The Sage recounted, “When the Waves of Destruction were washing over the world, that Ancient Demon came looking for me. After promising to make me a Demon King, he wanted to harvest my soul. He also promised to preserve my memories and grant me the position of a Greater Demon King that held authority beyond the reach of all the other Demon Kings of that era.”",
  "The current conversation had gone far beyond Carmen’s ability to comprehend it. In the first place, the only shared past that she was familiar with was the era of the war from three hundred years ago and the fact that Eugene was the reincarnation of Hamel. The Waves of Destruction? Agaroth? The Sage of the Ivory Tower? These were all topics that Carmen knew nothing about.",
  "However, Carmen didn’t express her curiosity and just kept her mouth shut as she quietly listened. Because in any case, the current topic of conversation regarding the true mythology of the world was enough for Carmen to feel extremely excited just by listening to it.",
  "“To me, that was an extremely… unpleasant and insulting offer. I had absolutely no desire to become a Demon King and continue to live a long and miserable life. And more than anything else, I hated the thought of subjecting my soul to that Ancient Demon’s chains.” The Sage let out a chuckle and gently patted Mary. “So I just threw Mary at him along with an insult. I told him that if he coveted my ability so greatly, he should just try and use my staff himself in the next era that he was so looking forward to.”",
  "“But what about the seal placed in Mary?” Sienna muttered in a dazed voice.",
  "At these words, the Sage burst out laughing, “Ahahaha! I was the one who left the seal there. Even if I was ready to meet my end, there was no way that I could leave my magic or my beloved Mary to a bunch of robbers without the respect or qualifications to use them correctly. That’s why I left the seal there. If an extremely talented young student of magic were able to break my seal someday, then he or she would truly be able to walk the same path as I did.”",
  "Unable to lift her jaw off the ground, Sienna just alternated between staring at the Sage and her staff, Mary, that the Sage was still holding in her hands. Currently, it had the appearance of a beautiful flower, but just moments ago, the staff that had been called the Bloody Mary had possessed a truly horrific appearance.",
  "Sienna’s expression twisted in disgust as she recalled the sight of Bloody Mary decorated with bones and bulging veins.",
  "“Was that grotesque appearance also due to your bad taste?” Sienna questioned with a grimace.",
  "The Sage shouted, “Don’t be so absurd! There’s no way that I would put such ominous ornamentation on my dear Mary! I had nothing to do with that appearance!”",
  "“Well, that makes sense,” Sienna said with a quick change of expression as she nodded her head.",
  "Although there was no way to know the full details behind it, it wasn’t hard to guess the reason for the change in appearance. That staff, Mary, was extremely unsuitable to be used for black magic in its original state. Frankly, there didn’t seem to be any traces of dark power within Mary’s current form. As such, the Demon King of Incarceration must have personally modified Mary, turning the flower at its head into a mass of dark power, then passing it on to his Staffs of Incarceration... but why hand it to them?",
  "‘It must have been because the Staffs of Incarceration were the most exceptional black wizards he could find,’ Sienna concluded.",
  "Sienna knew this from when she had looked through the memories that had been recorded in Bloody Mary. Belial was definitely one such example, but each of the black wizards who came before him also possessed extremely high levels of skill in black magic.",
  "However, even wizards of such skill hadn’t been able to break the seal left by the Sage….",
  "“You look relieved,” the Sage said as she looked at Eugene with a bright smile.",
  "“Why would I be relieved?” Eugene muttered defensively.",
  "“Do you really think that you could fool the eyes of a Sage? Idiot. I can clearly see what you were thinking. Didn’t you suspect that the Ancient Demon brutally murdered me and claimed Mary as his trophy?” the Sage said as she giggled teasingly.",
  "Unable to refute these words, Eugene stubbornly kept his mouth shut.",
  "To be honest, after the Sage had made her sudden appearance and the dark power of Incarceration began to flow out of the Bloody Mary, wouldn’t it have been strange if he hadn’t come up with such ominous thoughts when the Sage had called out my Mary?",
  "“So, what exactly is going on with you?” Eugene asked once he had managed to get a hold of his expression.",
  "He didn’t want to wait any longer or… spend any more time imagining what her answer might be. In the end, the answer that he was eagerly awaiting was something that Eugene, no, that Agaroth desperately wanted to know. Agaroth had dearly wanted to know what had happened after he was slain by the Demon King of Destruction.",
  "“Hold on,” Carmen suddenly spoke up. So far, she had been listening quietly to everything from the side.",
  "Eugene couldn’t help but feel concerned about what Carmen might say after hearing her suddenly interject like this.",
  "Everything they had just been talking about were topics that he had purposely kept from Carmen. They were things that she didn’t need to know, and if at all possible, Eugene also didn’t want her to know anything about them. All of this talk about the past era, a time that went even further back than the so-called good old days, would only serve to confuse those who belonged to the current era.",
  "Surprisingly, Carmen addressed this issue herself, “I won’t listen in on this any longer.”",
  "Hiding her excitement and pounding heart, Carmen deliberately put on a facade of calmness. If Melkith were in her position, she would surely have shrieked like a crow while listening to the story and would have kept trying to join in on their conversation, but Carmen wasn’t that type of person.",
  "Carmen might not be particularly self-aware, but everyone who had known Carmen for a long enough time was surprised to find that Carmen was someone with an amazing amount of tactfulness….",
  "“I don’t feel like I should keep listening to the topics that you will be discussing from this point onwards. To be honest, I am curious to hear more, but… at the same time, I feel afraid to keep listening. I am aware that there are truths about the world that I don’t necessarily need to know,” Carmen admitted before politely bowing her head and placing her clenched fist over her left breast. “Such truths will only restrict the way that I picture the world to be. It might even cause me to feel unfairly frustrated with my ignorance. I have no desire to experience such a thing.”",
  "Carmen’s voice was very calm as she gave her opinions. Eugene stared at Carmen while feeling a mixture of surprise and admiration. It occurred to him that, without such a strength of character, there was no way that Carmen would be so respected by her fellow knights.",
  "“How impressive,” the Sage murmured as she also nodded in admiration. “I admit that I was speaking without consideration for you latter generations. However, to rudely evict someone after inviting them into this place would only besmirch my honor. As such, I, Vishur Laviola, ask you, my distant descendant, how should I address you?”",
  "“I am the Silver Lion of the radiant Lionheart clan. My name is Carmen Lionheart,” Carmen introduced herself as she raised her bowed head and looked up at the Sage.",
  "The lion sigil on her left chest gleamed with a radiant light, and Carmen’s golden eyes also shone with the same kind of bright glow.",
  "After once again admiring Carmen’s resolve, the Sage spoke once more, “Carmen Lionheart, what is it that you desire currently? If there is something that you want, I can grant you a single wish if that is within my means to assist you with.”",
  "“I came to this forest looking for an adventure,” Carmen said carefully.",
  "Squeeze.",
  "The fist that she was holding to her chest clenched even tighter as Carmen continued, “I have already experienced the adventure that I was hoping for. Although I haven’t spent all that much time wandering through this forest, it would be no exaggeration to say that what I have experienced here were some of the most magical moments of my entire life. However, I do feel disappointed that there was a lack of any trials that should accompany such an adventure.”",
  "The Sage nodded as she said, “Indeed, so it is trials that you desire? Allow me to ask you, oh Carmen Lionheart, what is your purpose for seeking such trials?”",
  "“It is because I wish to walk together with Eugene on his path to the future,” Carmen replied with an unwavering, confident voice.",
  "Eugene couldn’t help but be moved once more by such a resolute answer.",
  "The Sage smiled proudly as she nodded her head. “Very good. Oh Carmen Lionheart, fortunately, I am able to accommodate your wish.”",
  "The Sage raised Mary high.",
  "Grrrrrrr!",
  "A short distance away, the ground began to shake, and then the roots of the World Tree erupted from their resting place deep within the earth. The roots that were sticking up out of the ground tangled around each other and then clumped together in the form of a hemisphere.",
  "“Head in there,” the Sage instructed as the roots parted slightly, creating a passage. “There is an enemy inside who will teach you the true meaning of death. Within that place, you will experience death hundreds of times over, but you will never actually die. However, the experience of being repeatedly put on the verge of death should be enough to provide you with the trials that you have found yourself seeking.”",
  "“Ah!” Carmen let out an excited gasp.",
  "She didn’t ask just what was waiting for her inside because she wanted to check it out herself without hearing anything beforehand. After bowing her head deeply in gratitude towards the Sage, Carmen ran towards the roots.",
  "Eugene hadn’t really felt the need to ask any questions either. However, when he saw that the ball of roots that Carmen had entered was starting to convulse like it was a living creature, he had a thought that he should at least have asked for some information beforehand.",
  "“What exactly is in there?” Eugene asked suspiciously.",
  "“It’s the God of Giants,” the Sage responded casually.",
  "Everyone was shocked by this answer as they turned to stare at the Sage.",
  "“Hmm, I can see how my words might have some room for misunderstanding. To be more precise, it is the God of Giants recreated from my memory,” the Sage elaborated.",
  "“From your memory?” Eugene repeated.",
  "“It isn’t the real thing or even a clone of the real thing. However, since I have completely reproduced the strength of the God of Giants from what I remember of him, it won’t be easy for her even to stay alive, let alone win against him,” the Sage said.",
  "The Sage didn’t have any malice driving her actions. She had truly been impressed by Carmen’s spirit and had simply provided Carmen with the trial that the knight had so desired while using her discretion in setting the level of the trial. Yet even so, Eugene couldn’t help but give the Sage a look of reproval.",
  "Agaroth’s memories hadn’t left him with many recollections of the Sage or the God of Giants. Only fragmentary impressions of the two remained.",
  "The God of Giants was just as barbarically huge and powerful as his name suggested. Because his body was so immense, he usually shrunk himself down to the size of a hulking man whenever he needed to go anywhere, but even when he reduced his size like this, his strength would barely even decrease. Even Agaroth himself wouldn’t be a match for the God of Giants in a simple contest of strength.",
  "No matter how strong Carmen might be, in the end, she was still on the level of a human. Even if she was close to the upper boundary of that level, this meant that she was still within human limits. It was impossible for her to fight against the God of Giants.",
  "The Sage defended herself, “If someone were to experience death hundreds of times, even a complete fool would be able to learn something. Since Carmen Lionheart is nowhere near a fool, she will surely be able to gain that much more from the experience.”",
  "“So you’re planning on killing her hundreds of times over?” Eugene asked disapprovingly.",
  "The Sage shrugged, “That depends on her strength of will. The flow of time out here and in there is different, but she’ll be able to come out of there whenever she wants. If her will is as strong as iron, she should certainly be able to gain something from this ordeal.”",
  "It was only natural to obtain something after enduring so much suffering. However, even Eugene thought that such a method was extremely, extremely reckless. Eugene had also attempted that type of training in the past — back in the Darkroom beneath the Lionheart mansion.",
  "In that place where even if one died, one wouldn’t actually perish in reality, Eugene had fought against an illusion of the ideal version of himself based on the image that he was able to picture at that time. Eugene wasn’t the only one to have partaken in such training. Previously, Carmen had also overcome such a trial in the Darkroom.",
  "However, the difference between Carmen and her opponent this time was far too great. The gap between Carmen and the illusion in the Darkroom would still have left her able to put up somewhat of a fight, but… if what appeared within that ball of roots was the true God of Giants — then Carmen wouldn’t even be able to land a single blow on him successfully.",
  "“Even if she doesn’t want to, she’ll be forced to metamorphose,” Eugene muttered to himself.",
  "The Sage smiled and lowered Mary before asking, “Now then, shall I continue the story? Agaroth, you were curious about how I died, weren’t you?”",
  "“Yeah.” Eugene slowly nodded.",
  "“Ahaha, I enjoy hearing your honest opinions about me. Junior, those words apply to you as well,” the Sage said as she shook the lapels of her robes, which were identical to Sienna’s. “Junior, I know what you were thinking. I know why you were so shocked when I appeared in front of you as a figure of light. Junior, you thought that your true identity was the reincarnation of me, Vishur Laviola, isn’t that right?”",
  "“It’s because I thought we were eerily similar,” Sienna mumbled in response.",
  "After hearing such words from the Sage, Sienna couldn’t help but feel embarrassed.",
  "“Junior, you aren’t me,” the Sage stated firmly. “My soul was extinguished immediately upon my death. What remains here is just an echo that was summoned by your voice.”",
  "Eugene’s expression couldn’t help but harden at the loneliness he heard in the Sage’s voice.",
  "“Just what exactly happened to you?” Eugene asked once more.",
  "Mary, which the Sage was still holding, began to glow. Soon, petals scattered from it.",
  "“Agaroth, I saw the end that you were no longer around to see,” the Sage whispered.",
  "The multiplying cloud of flower petals violently rushed toward him and engulfed Eugene’s entire vision.",
  "When the petals lifted… Eugene saw a wasteland covered in corpses.",
  "Openbookworm & DantheMan's Thoughts",
  "OBW: Time for Carmen’s training montage. I wonder how much stronger she will be when she emerges.",
  "Momo: Carmen has consistently been one of my favorite characters. Can’t wait to see her grow.",
];
